version: '3.8'

services:
  postgres-auth:
    image: postgres:17
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${DB_NAME_AUTH}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro-network

  postgres-client:
    image: postgres:17
    container_name: postgres-client
    environment:
      POSTGRES_DB: ${DB_NAME_CLIENT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-client:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro-network

  postgres-order:
    image: postgres:17
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${DB_NAME_ORDER}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata-order:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro-network
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - kafka:/kafka/logs

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      postgres-auth:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      REDIS_HOST: ${REDIS_HOST}
      SPRING_DATASOURCE_URL: ${DB_URL_AUTH}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      JWT_TTL_KEY: ${JWT_TTL_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_TTL_KEY: ${JWT_REFRESH_TTL_KEY}
    ports:
      - "8081:8081"
    networks:
      - micro-network
    restart: unless-stopped

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      postgres-order:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_ORDER}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "8084:8084"
    networks:
      - micro-network
    restart: unless-stopped

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile
    container_name: customer-service
    depends_on:
      postgres-client:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_CLIENT}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "8083:8083"
    networks:
      - micro-network
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8082:8082"
    networks:
      - micro-network
    restart: unless-stopped

volumes:
  pgdata-auth:
  pgdata-client:
  pgdata-order:
  kafka:

networks:
  micro-network:
    driver: bridge