version: '3.8'

services:
  postgres-auth:
    image: postgres:17
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ENV_DB_NAME_AUTH
      POSTGRES_USER: ENV_DB_USER
      POSTGRES_PASSWORD: ENV_DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - micro-network

  postgres-client:
    image: postgres:17
    container_name: postgres-client
    environment:
      POSTGRES_DB: ENV_DB_NAME_CLIENT
      POSTGRES_USER: ENV_DB_USER
      POSTGRES_PASSWORD: ENV_DB_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - pgdata-client:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U client_user -d client_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - micro-network

  postgres-order:
    image: postgres:17
    container_name: postgres-order
    environment:
      POSTGRES_DB: ENV_DB_NAME_ORDER
      POSTGRES_USER: ENV_DB_USER
      POSTGRES_PASSWORD: ENV_DB_PASSWORD
    ports:
      - "5434:5432"
    volumes:
      - pgdata-order:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order_user -d order_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - micro-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro-network
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: ENV_KAFKA_NODE_ID
      KAFKA_PROCESS_ROLES: ENV_KAFKA_PROCESS_ROLES
      KAFKA_LISTENERS: ENV_KAFKA_LISTENERS
      KAFKA_ADVERTISED_LISTENERS: ENV_KAFKA_ADVERTISED_LISTENERS
      KAFKA_CONTROLLER_LISTENER_NAMES: ENV_KAFKA_CONTROLLER_LISTENER_NAMES
      KAFKA_CONTROLLER_QUORUM_VOTERS: ENV_KAFKA_CONTROLLER_QUORUM_VOTERS
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ENV_KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      KAFKA_INTER_BROKER_LISTENER_NAME: ENV_KAFKA_INTER_BROKER_LISTENER_NAME
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ENV_KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      KAFKA_LOG_DIRS: ENV_KAFKA_LOG_DIRS
      CLUSTER_ID: ENV_CLUSTER_ID

volumes:
  pgdata-auth:
  pgdata-client:
  pgdata-order:

networks:
  micro-network:
    driver: bridge